#!/usr/bin/php
<?php   
require __DIR__ . '/core/main.class.php';
use RuParser\RuParser as Parser; 

$time = microtime(true);

    //პარსერის დაკონფიგურება. 
    $parser = new Parser([
        'welcome' => 'RuPaser'
    ]);    

    $a = $parser->getHtmlbyPage('KinoGo', 'http://kinogo.eu/', '2');     
    $parser->MultiCurlRequest($a); 
    
    echo  "\n" . (microtime(true) - $time ) . "\n";
  
?>