#!/usr/bin/php
<?php   
require __DIR__ . '/core/main.class.php';
use RuParser\RuParser as Parser; 
$time = microtime(true);
    //პარსერის დაკონფიგურება. 
    $parser = new Parser([
        'welcome' => 'RuPaser'
    ]);

    for($i=0; $i<2; $i++){
        $links = $parser->getHtmlbyPage('KinoGo', 'http://kinogo.eu/', $i);

        $parser->MultiCurlRequest($links); 

    }

    //$parser->DB_TEST(); 

    // $parser->saveInDB([
    //     'title' => 'this is a title', 
    //     'description' => 'this is a description', 
    //     'image' => 'https://www.test.com/dir/dir/dir/images.png',
    //     'content' => 'dsadsadsadasdadasldksal;daksdl;as,.>?.dsdl0-3r k dl;askd;lasd;la skdadad'
    // ]);

    echo  "\n" . (microtime(true) - $time ) . "\n";
  
?>